name: Deploy to Hostinger

on:
  push:
    branches:
      - main
      - 1-inicio-de-sesion

jobs:
  create-pull-request:
    if: github.ref == 'refs/heads/1-inicio-de-sesion'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: '1-inicio-de-sesion'
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'Auto merge 1-inicio-de-sesion into main'
          pr_body: 'This pull request was created automatically by GitHub Actions.'

      - name: Merge Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_request = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: '1-inicio-de-sesion'
            });

            if (pull_request.data.length > 0) {
              const pr_number = pull_request.data[0].number;
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number
              });
            }

      - name: Delete Branch
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/1-inicio-de-sesion'
            });

  deploy:
    runs-on: ubuntu-latest
    needs: create-pull-request
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: 65002
          script: |
            pwd
            cd /home/u691064313/domains/soudevteam.com
            git pull
            cp -r /home/u691064313/domains/soudevteam.com/public/ /home/u691064313/domains/soudevteam.com/public_html/
            pwd
