name: Deploy to Hostinger

on:
  push:
    branches:
      - main
      - 1-inicio-de-sesion

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to Hostinger via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        port: 65002
        script: |
          pwd
          cd /home/u691064313/domains/soudevteam.com
          git pull
          cp -r /home/u691064313/domains/soudevteam.com/public/ /home/u691064313/domains/soudevteam.com/public_html/
          pwd
