name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # o la rama que deseas desplegar automáticamente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        source: "./"
        target: "./domains/soudevteam.com/"

    - name: Run SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          cd /domains/soudevteam.com/
          # Aquí puedes ejecutar comandos para reiniciar servicios, instalar dependencias, etc.
          npm run build
